### ISSUE TITLE
retrieving ordered items per order request to be used for inventory summary

### ISSUE THREAD

**Issue by MarionJayMBalugo** [incrementtechnologies/project_rx_api#13]
![image](https://user-images.githubusercontent.com/53893630/91513172-48e8f380-e916-11ea-91d0-9612bd756f01.png)

Needed man gud nga makuha all the items in every orders per date sir.
But lahi man sya  og implementation compared sa inig click nimo sa eye nga icon sa table sir , I needed to iterate through the data fetch using 'checkouts/retrieve_orders' api to get the the item id need to retrieve every item associated with the order request using this api : 'checkout_items/retrieve_on_orders' . So ang ending sir kay daghan kaaung http request ang mahimo just to retrieve all the items per order of a certain date.

**Comment by kennCK** [comment]
@ecvelayo na resolve nani sya sir sa? Kindly close nalng sa issue if ever.

**Comment by kennCK** [comment]
Closing this now.
