### ISSUE TITLE
Wallet Routes

### ISSUE THREAD

**Issue by themonstrousdev** [incrementtechnologies/project_rx_api#9]
Need routes that auto combine and filter funds by the merchant.

Suggested data output:
```
[
   { balance: 12000, currency: 'PHP'},
   { balance: 100, currency: 'USD}
]
```

**Comment by kennCK** [comment]
@ecvelayo  please let me now once okay nani so that I can proceed.

**Comment by kennCK** [comment]
@themonstrousdev closing this now. Kindly check the routes document then use ledger/summary
